### ISSUE TITLE
replace separate pages with # in url

### ISSUE THREAD

**Issue by chexbox** [chexbox/AlgCalc#43]
With Javascript you can use window.location.hash to read a hash at the end of a url `window.location.hash` would return '#simple' for the url https://chexbox.github.io/Algebra-Calculator/#simple 

We would use this to get calculators from different iframes.

**Comment by infinitytec** [comment]
I don't think I understand.

**Comment by chexbox** [comment]
See updated post

**Comment by chexbox** [comment]
Oops deleted wrong post.
